name: CI - Tests Unittest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Tests avec unittest
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip

      - name: Lancer les tests unittest
        run: |
          python -m unittest discover -s . -p "test_*.py"

  deploy:
    name: Déploiement
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Rendre le script exécutable
        run: chmod +x deploy.sh

      - name: Lancer le script deploy.sh
        run: ./deploy.sh
